---
- name: Install a list of PHP packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - apache2
      - libapache2-mod-php
      - mariadb-server
      - php
      - php-bcmath
      - php-common
      - php-ctype
      - php-gd
      - php-iconv
      - php-intl
      - php-json
      - php-mbstring
      - php-mysql
      - unzip
# vim: ts=4 sw=4 sts=4 sr noet
