- name: Upload mysql template file
  template:
    src: templates/wacko.sql.j2
    dest: /tmp/wacko.sql
    mode: '0640'

- name: Does mysql template file exists?
  stat:
    path: /tmp/wacko.sql
  register: register_wacko_sql

- name: Setup wacko mysql
  shell: |
    mysql < /tmp/wacko.sql
  when: register_wacko_sql.stat.exists
